### ISSUE TITLE
[ENHANCE] Implement adaptive parser for various web domains

### ISSUE THREAD

**Issue by Jungjihyuk** [Rimember/ringchat#51]
### Search before adding issue

- [X] I have searched the ringchat [issues](https://github.com/Rimember/ringchat/issues) and found no similar feature request.

### Description

새로운 종류의 URL이 첨부되도 일정 수준 이상의 파싱이 가능하도록 파서 구현. 

### Todo

- [x] 일반적인 문서 파싱 방법 조사 
- [x] parser.py 파일에 파서 구현
