### ISSUE TITLE
[FEAT] 추천된 링크 표시할 때 link_title 표시

### ISSUE THREAD

**Issue by Jungjihyuk** [Rimember/ringchat#54]
### Search before adding issue

- [X] I have searched the ringchat [issues](https://github.com/Rimember/ringchat/issues) and found no similar feature request.

### Description

사용자가 링크 검색하기 기능을 통해 표시된 링크 목록에서 각 링크에 해당하는 간단한 내용을 표시하려고 한다. 
간단한 내용은 이미 존재하는 link_title 컬럼의 값을 표시하려 한다. 

### Todo

- [x] 링크 검색 모달창안에 링크 표시하는 리스트 수정 
- [x] 링크 추천시 링크, 링크 타이틀 같이 불러오도록 수정
