### ISSUE TITLE
[FEAT] 채팅방 즐겨찾기 UI 및 로직 구현

### ISSUE THREAD

**Issue by NBHDQXT** [Rimember/ringchat#62]
### Search before adding issue

- [X] I have searched the ringchat [issues](https://github.com/Rimember/ringchat/issues) and found no similar feature request.

### Description

채팅방을 즐겨찾기 버튼 및 표현에 대한 UI를 구현하고, DB와의 연동을 통해 즐겨찾기 정보를 송수신할 수 있도록 구현할 예정입니다.

### Todo

- [ ] 즐겨찾기 버튼 생성 및 표현 UI 구현
- [ ] 즐겨찾기 정보 DB에 저장 로직 구현
- [ ] 즐겨찾기된 채팅방이 상위노출 되도록 정렬 기능 구현
